### ISSUE TITLE
Are any top-level properties required?

### ISSUE THREAD

**Issue by balhoff** [dosumis/dead_simple_owl_design_patterns#29]
In the JSON schema, the top-level definition for a pattern doesn't have a `required:` array. Is this because no property is absolutely required? I am guessing that's the case, wondering about `pattern_name`.

**Comment by dosumis** [comment]
Want to keep it minimal for flexibility, but seems reasonable to have pattern_name.  No closure specified either in order to allow extensions,  but it could be useful to have a stricter version with closure.

**Comment by balhoff** [comment]
Makes sense, thanks, I am keeping everything optional in my implementation for now.
