### ISSUE TITLE
Rules for synonyms - how to cope with these?

### ISSUE THREAD

**Issue by dosumis** [dosumis/dead_simple_owl_design_patterns#3]

**Comment by cmungall** [comment]
A basic synonym scope algebra for combining concepts:

    E x E -> E
    R x R -> R
    N x N -> N
    B x B -> B
    anything else -> R

Rules for synonym types are other properties will likely be domain-specific. But some general ones:

 * two abbrevations should never be combined
 * an abbreviation can be combined with a non-abbreviation (e.g. "ER transport"), the result is not a true abbreviation

I think it might be useful to have a type for trivial lexical shuffling. For example, a display may want to hide "development of lung" if the primary label is "lung development".

In general it would be useful to track evidence for a synonym, so we can do cascading deletes. I wonder how many stale synonyms we have in GO, or cases where we need to auto-fill.

**Comment by dosumis** [comment]
Plan to add the ability to specify regex patterns.   Synonyms can the be specified by a mix of concatenation & regex given input synonyms.

**Comment by dosumis** [comment]
Scope algebra looks good.

**Comment by hdietze** [comment]
One thing we use in TG to exclude synonyms are (custom) scopes. For example PO has a custom scope for non-english translations, which should be avoided for the synonym generation. 
Maybe consider a white list or a black list of scopes as configuration option.

What should be included/excluded is often driven by the external ontology and how the use synonyms (i.e. ChEBI IUPAC synonyms are not useful).

**Comment by cmungall** [comment]
Good point

This could be configured either within the template, or as some kind of 
additional parameter or conf file passed in to the generator. The latter 
has the advantage of not complicating the pattern language. Also some 
rule may end up being procedural, which also points to outside 
configuration.

**Comment by dosumis** [comment]
#32
