### ISSUE TITLE
IRI column in input

### ISSUE THREAD

**Issue by balhoff** [dosumis/dead_simple_owl_design_patterns#30]
Is the name of the IRI column in the input CSV standardized by the spec? I've seen `iri`, and @cmungall recommended `defined_class` at one point. This could also be command line option.

**Comment by cmungall** [comment]
Not AFAIAW.

defined_class may be too restrictive. DPs can also provide SubClassOf axioms, no Equiv Axioms. And with instance patterns, the IRI may be an OWL Individual.

Another option is to privilege col1/2 by default

**Comment by dosumis** [comment]
Broader issue is building spec for tsv input.  I've avoided this on DOSDP up to now, considering this an issue for implementations, but perhaps that was silly.  

- [ ] TODO add a simple doc with TSV spec.  Needs: header name for IRI column; spec for how to delimit lists.  Anything else?

**Comment by dosumis** [comment]
See #38
