### ISSUE TITLE
Add INSTALL.md or description of how to run to README

### ISSUE THREAD

**Issue by cmungall** [dosumis/dead_simple_owl_design_patterns#4]

**Comment by cmungall** [comment]
I hacked something together to get jars on my classpath, abstract_pattern_runner works.

`pattern.applied_pattern` looks like it's ready to go, but nothing seems to use it - something not checked in, or did development just stall at this point?

**Comment by dosumis** [comment]
Used for Roche project, but not much else yet.

**Comment by dosumis** [comment]
Will set up mvn import specifying java imports. Playing with packaging jython as jars.  Will have a go at rolling one for release of this project.

**Comment by dosumis** [comment]
Documentation summarising basic usage here: https://github.com/dosumis/dead_simple_owl_design_patterns/blob/master/src/README.md

**Comment by cmungall** [comment]
any progress on this / help needed?

**Comment by dosumis** [comment]
No longer relevant.
