### ISSUE TITLE
Is the OBO prefix assumed?

### ISSUE THREAD

**Issue by cmungall** [dosumis/dead_simple_owl_design_patterns#5]
I'd like to use this for some non-OBO ontologies but there seems to be
an assumption about the OBO prefix. I hope this isn't hardwired all
the way into Brain. For other projects, e.g. Robot we've been using
CURIE prefixes.

Ideally the use could declare either prefixes (and use CURIEs like GO:nnnnn) or a base prefix (OK to assume OBO as default for backwards compatibility)

**Comment by dosumis** [comment]
The assumption of Brain is that short form IDs are sufficient to disambiguate entities within any one Brain object.  The underlying base URIs can vary.  DOS-DP has this assumption too. Validation checks all referenced entities against a reference Brain object - in which the ontology to be used for term generation is loaded.

**Comment by dosumis** [comment]
For URI generation: I've kept this outside of templates for now (ie -up to implementing scripts).  Straightforward to add. Doesn't have to be restricted to OBO- style.

**Comment by dosumis** [comment]
Some doc here:

https://github.com/dosumis/dead_simple_owl_design_patterns/blob/master/src/README.md
