### ISSUE TITLE
Combine md and yaml?

### ISSUE THREAD

**Issue by cmungall** [dosumis/dead_simple_owl_design_patterns#6]
Seems you have both md and yaml files. These could be combined, with the YAML inside a `---` block in the md, as in the ontology md files here: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/, e.g. [fbbt](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/fbbt.md)

Maybe this adds an extra annoying processing step, but there is some advantage to keeping things in one place

YMMV, close if irrelevant.

**Comment by cmungall** [comment]
Oh I see, the md is made from the yaml rather than maintained separately

**Comment by dosumis** [comment]
One of my aims with this was (is) to automate documentation.  Generated md was a start at that.
